services:
  mariadb:
    image: mariadb:mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception_net_hamrachi
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3306"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: always

  wordpress:
    image: wordpress:wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception_net_hamrachi
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx:nginx
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception_net_hamrachi
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/hamrachi/data/mariadb
      type: none
      o: bind

  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/hamrachi/data/wordpress
      type: none
      o: bind

networks:
  inception_net_hamrachi:
    driver: bridge